site_info:
  diameter_m: 0.2
  slope: 0.0072

# Data arrays
observations:
  depths: [
    0.039, 0.046, 0.053, 0.058, 0.065, 0.071, 0.076, 0.081, 0.095
  ]
  velocities: [
    0.42, 0.46, 0.50, 0.53, 0.57, 0.61, 0.62, 0.66, 0.69
  ]

settings:
  model_path: "../models/silt_cnn/trained_model.keras"
  output_dir: "../data/input_plots"