# Site Information: pipe diameter [in meter] and slope [rise/run]
site_info:
  diameter_m: 0.2
  slope: 0.0072

# Data arrays: flow depths [in meter] and velocities [in m/s]
# observed values Exp1 (silt depth: 0 m)
observations:
  depths: [
    0.03959596,0.03959596,0.046666667,0.046666667,0.046464646,0.053535354,
    0.053535354,0.058585859,0.058585859,0.065656566,0.065656566,0.071111111,
    0.072121212,0.076565657,0.076565657,0.075959596,0.074545455,0.081212121,
    0.081010101,0.087070707,0.095757576,0.095353535
  ]
  velocities: [
    0.427590848,0.417092867,0.462314939,0.463122476,0.463122476,0.507537012,
    0.500269179,0.539030956,0.534993271,0.577792732,0.573755047,0.614131898,
    0.600403769,0.615746972,0.626244953,0.631897712,0.638358008,0.661776581,
    0.662584118,0.686002692,0.695693136,0.69730821
  ]

settings:
  model_path: "../models/silt_cnn/trained_model.keras"
  output_dir: "../data/input_plots"