# Site Information: pipe diameter [in meter] and slope [rise/run]
site_info:
  diameter_m: 0.2
  slope: 0.0072

# Data arrays: flow depths [in meter] and velocities [in m/s]
# observed values Exp1 (silt depth: 0.075 m)
observations:
  depths: [
   0.101818182,0.107575758,0.113333333,0.116060606,0.123939394,0.13030303,
   0.134242424,0.14030303,0.144545455,0.152424242
  ]
  velocities: [
    0.118548387,0.147580645,0.18266129,0.211693548,0.249193548,0.279435484,
    0.302419355,0.335080645,0.360483871,0.400403226
  ]

settings:
  model_path: "../models/silt_cnn/trained_model.keras"
  output_dir: "../data/input_plots"